{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Lab1run.ipynb",
      "provenance": [],
      "collapsed_sections": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 37,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "2ooBH1aPf9rg",
        "outputId": "a285f046-2c3e-40aa-edcd-3e7061e42d5d"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Enter the number of students: 1\n",
            "Enter the student 1 information:\n",
            "1. ID: 1\n",
            "2. Name: La\n",
            "3. DoB: 1/3/2009\n",
            "[{'Name': 'La', 'ID': '1', 'DoB': '1/3/2009'}]\n",
            "1 student's information is entered successfully!\n",
            "Enter the number of courses: 1\n",
            "Enter the course 1 information:\n",
            "1. IDC: 1\n",
            "2. NameC: math\n",
            "[{'IDC': '1', 'NameC': 'math'}]\n",
            "1 course's information is entered successfully!\n",
            "Listing 1 students\n",
            "{'Name': 'La', 'ID': '1', 'DoB': '1/3/2009'}\n",
            "Listing 1 courses\n",
            "{'IDC': '1', 'NameC': 'math'}\n",
            "Enter the course's ID or the course's name you want to select: 1\n",
            "Enter student's1mark: 10\n",
            "Student's mark is entered successfully!\n",
            "Listing 2 marks\n",
            "{'Name': 'La', 'ID': '1', 'DoB': '1/3/2009'}\n",
            "{\"Student's mark\": 10}\n"
          ]
        }
      ],
      "source": [
        "def inputStudentNums():\n",
        "    while  True:\n",
        "      studentNums = int(input(\"Enter the number of students: \"))\n",
        "      if studentNums>0:\n",
        "            break\n",
        "      else:\n",
        "            print(\"Invalid input, please try again!\")\n",
        "    return studentNums\n",
        "\n",
        "def inputStudentInfo(studentNums):\n",
        "    ST =[]\n",
        "    for i in range(studentNums):\n",
        "        print(f\"Enter the student \" + str(i+1) + \" information:\")\n",
        "        idst = input(\"1. ID: \")\n",
        "        namest = input(\"2. Name: \")\n",
        "        dob = input(\"3. DoB: \")\n",
        "        ST.append({\n",
        "           \"Name\": namest,\n",
        "           \"ID\": idst,        \n",
        "           \"DoB\": dob\n",
        "        })\n",
        "    print(ST)\n",
        "    print(f\"{studentNums} student's information is entered successfully!\")\n",
        "    return ST\n",
        "\n",
        "def inputCourseNums():\n",
        "    while  True:\n",
        "      courseNums = int(input(\"Enter the number of courses: \"))\n",
        "      if courseNums>0:\n",
        "            break\n",
        "      else:\n",
        "            print(\"Invalid input, please try again!\")\n",
        "    return courseNums\n",
        "\n",
        "def inputCourseInfo(courseNums):\n",
        "    CS =[]\n",
        "    for i in range(courseNums):\n",
        "        print(f\"Enter the course \" + str(i+1) + \" information:\")\n",
        "        idc = input(\"1. IDC: \")\n",
        "        namec = input(\"2. NameC: \")\n",
        "        CS.append({\n",
        "           \"IDC\": idc,        \n",
        "           \"NameC\": namec\n",
        "        })\n",
        "    print(CS)\n",
        "    print(f\"{courseNums} course's information is entered successfully!\")\n",
        "    return CS\n",
        "\n",
        "def ListCourse(CS):\n",
        "    print(f\"Listing {len(CS)} courses\")\n",
        "    for course in CS:\n",
        "          print(course)\n",
        "\n",
        "def ListStudents(ST):\n",
        "    print(f\"Listing {len(ST)} students\")\n",
        "    for student in ST:\n",
        "          print(student)\n",
        "\n",
        "def courseSelect(CS):\n",
        "    c = input(\"Enter the course's ID or the course's name you want to select: \")\n",
        "    for i in range(0, len(CS)):\n",
        "      if c == CS[i]['IDC'] or c == CS[i]['NameC']:\n",
        "         return('The selected course is:', [CS[i]])\n",
        "         break\n",
        "      elif i == (len(CS)-1):\n",
        "         print(\"This course is not in the list, please try again!\"\n",
        "\n",
        "def inputStudentMarkforCourse(ST):\n",
        "    for i in range(len(ST)):\n",
        "       mcs= int(input(\"Enter student's \" + str(i+1) + \" mark: \"))\n",
        "       while True:\n",
        "         if(mcs>=0 and mcs<=20): break\n",
        "         else: print(\"Invalid input, please try again!\")\n",
        "       ST.append({\n",
        "           \"Student's mark\": mcs\n",
        "       })\n",
        "    print(\"Student's mark is entered successfully!\")\n",
        "    return ST\n",
        "\n",
        "def showMarks(ST):\n",
        "    print(f\"Show student's marks\")\n",
        "    for mark in ST:\n",
        "          print(mark)\n",
        "\n",
        "studentNums = inputStudentNums()\n",
        "ST = inputStudentInfo(studentNums)\n",
        "courseNums = inputCourseNums()\n",
        "CS = inputCourseInfo(courseNums)\n",
        "ListStudents(ST)\n",
        "ListCourse(CS)\n",
        "courseSelect(CS)\n",
        "inputStudentMarkforCourse(ST)\n",
        "showMarks(ST)"
      ]
    }
  ]
}